trigger:
  branches:
    include:
      - main

stages:
- stage: Setup_Linux
  jobs:
  - job: InstallMySQL_Apache
    pool:
      name: linux-agent
    steps:
    - checkout: self  # تأكد من تنزيل الكود من GitHub
    - script: |
        sudo yum update -y
        sudo yum install -y httpd mysql-server
        sudo systemctl start httpd
        sudo systemctl enable httpd
        sudo firewall-cmd --add-service=http --permanent
        sudo firewall-cmd --reload
    - script: |
        sudo mysql -u root -e "source $(Build.SourcesDirectory)/src/database/init.sql"
      displayName: 'Run MySQL Script'
    - script: |
        sudo cp -r $(Build.SourcesDirectory)/src/* /var/www/html/
      displayName: 'Copy Web Files to Apache Root'

- stage: Setup_Windows
  jobs:
  - job: InstallIIS_MySQL
    pool:
      name: windows-agent
    steps:
    - checkout: self  # تأكد من تنزيل الكود من GitHub
    - powershell: |
        Install-WindowsFeature -Name Web-Server -IncludeManagementTools
        net start W3SVC
      displayName: 'Install IIS and Start Service'
    - powershell: |
        mysql -u root -e "source $(Build.SourcesDirectory)\src\database\init.sql"
      displayName: 'Run MySQL Script'
    - powershell: |
        Copy-Item -Path "$(Build.SourcesDirectory)\src\*" -Destination "C:\inetpub\wwwroot" -Recurse -Force
      displayName: 'Copy Web Files to IIS Root'
