trigger:
  branches:
    include:
      - main

stages:
- stage: Setup_Linux
  jobs:
  - job: InstallMySQL_Apache
    pool:
      vmimage: RHELRaw8LVMGen2
    steps:
    - script: |
        sudo yum update -y
        sudo yum install -y httpd mysql-server
        sudo systemctl start httpd
        sudo systemctl enable httpd
        sudo firewall-cmd --add-service=http --permanent
        sudo firewall-cmd --reload
        mysql -u root -e "source src/database/init.sql"
        cp -r src/* /var/www/html/

- stage: Setup_Windows
  jobs:
  - job: InstallIIS_MySQL
    pool:
      name: windows-agent
    steps:
    - powershell: |
        Install-WindowsFeature -Name Web-Server -IncludeManagementTools
        net start W3SVC
        mysql -u root -e "source src\\database\\init.sql"
        Copy-Item -Path src/* -Destination C:\inetpub\wwwroot -Recurse -Force
